export const PUSHER_EVENTS = {
  SUBSCRIPTION_SUCCEEDED: 'pusher:subscription_succeeded',
  MEMBER_ADDED: 'MEMBER_JOIN_TO_ROOM',
  MEMBER_REMOVED: 'MEMBER_LEFT_ROOM',
  VOTED: 'voted',
  SHOW_VOTES: 'SHOW_VOTES',
  REVEAL_VOTES: 'REVEAL_VOTES',
  RESET_VOTES: 'RESET_VOTES',
  USER_ID: (id: string) => `USER_ID:${id}`,
  PAPER_THROWN: 'PAPER_THROWN',
};
