version: '3.9'

services:

  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: planning-poker
    ports:
      - "5432:5432"
