import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from 'next-themes';
import type { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider>
          <div className="h-screen flex flex-col">
            {children}
            <div className="mt-auto">
              <footer className="p-2 text-xs text-center mt-6 bg-gray-100 dark:bg-gray-900">
                <a
                  href="https://sebastiansiejek.dev"
                  target="_blank"
                  rel="nofollow"
                  className="transition hover:text-primary-500"
                >
                  sebastiansiejek.dev
                </a>
              </footer>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
