name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_run:
    workflows: [ CI ]
    types:
      - completed
  workflow_dispatch:

jobs:
  Deploy-Preview:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch != 'main') }}
    runs-on: ubuntu-latest
    environment: Preview

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Run build steps
        run: echo "Building on branch ${{ github.event.pull_request.head.sha }} - ${{ github.ref }} - ${{ github.event.workflow_run.head_branch }}"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
